server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${APP_NAME}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_SERVER_URL}/realms/${KEYCLOAK_REALM}
          jwk-set-uri: ${KEYCLOAK_SERVER_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs

#  SERVICE DISCOVERY 
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

#  CUSTOM PROPERTIES 
gateway:
  external-url: ${GATEWAY_EXTERNAL_URL}

keycloak:
  server-url: ${KEYCLOAK_SERVER_URL}
  external-url: ${KEYCLOAK_EXTERNAL_URL}
  realm: ${KEYCLOAK_REALM}

#  DOCUMENTATION 
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Super Skylab API
        url: /v3/api-docs/super-skylab
      - name: Forms API
        url: /v3/api-docs/formsapi
    oauth:
      client-id: ${SWAGGER_CLIENT_ID}
      use-pkce-with-authorization-code-grant: true
      scopes:
        - openid
        - profile
        - email
    config-url: /v3/api-docs/swagger-config
  api-docs:
    enabled: true
  show-actuator: false