version: '3.8'

services:
  rabbitmq:
    container_name: super-skylab-rabbitmq
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: rabbitMQ
      RABBITMQ_DEFAULT_PASS: rabbitMQ
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - nginx-network

volumes:
  rabbitmq_data:


networks:
  nginx-network:
    external: true